# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClientGET.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientGET(object):
    def setupUi(self, ClientGET):
        ClientGET.setObjectName("ClientGET")
        ClientGET.resize(581, 443)
        self.gridLayout = QtWidgets.QGridLayout(ClientGET)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.functionButton = QtWidgets.QPushButton(ClientGET)
        self.functionButton.setObjectName("functionButton")
        self.horizontalLayout.addWidget(self.functionButton)
        self.variableButton = QtWidgets.QPushButton(ClientGET)
        self.variableButton.setObjectName("variableButton")
        self.horizontalLayout.addWidget(self.variableButton)
        self.resetButton = QtWidgets.QPushButton(ClientGET)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.runButton = QtWidgets.QPushButton(ClientGET)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(ClientGET)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("LM Mono Caps 10")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.urlText = QtWidgets.QLabel(ClientGET)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(14)
        self.urlText.setFont(font)
        self.urlText.setObjectName("urlText")
        self.horizontalLayout_2.addWidget(self.urlText)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(ClientGET)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.functionText = QtWidgets.QPlainTextEdit(ClientGET)
        self.functionText.setObjectName("functionText")
        self.verticalLayout_2.addWidget(self.functionText)
        self.label_4 = QtWidgets.QLabel(ClientGET)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.variablesText = QtWidgets.QPlainTextEdit(ClientGET)
        self.variablesText.setObjectName("variablesText")
        self.verticalLayout_2.addWidget(self.variablesText)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.results = QtWidgets.QTreeWidget(ClientGET)
        self.results.setObjectName("results")
        self.results.headerItem().setText(0, "1")
        self.horizontalLayout_3.addWidget(self.results)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(ClientGET)
        QtCore.QMetaObject.connectSlotsByName(ClientGET)

    def retranslateUi(self, ClientGET):
        _translate = QtCore.QCoreApplication.translate
        ClientGET.setWindowTitle(_translate("ClientGET", "Dialog"))
        self.functionButton.setText(_translate("ClientGET", "Set Function"))
        self.variableButton.setText(_translate("ClientGET", "Add Variable"))
        self.resetButton.setText(_translate("ClientGET", "Reset"))
        self.runButton.setText(_translate("ClientGET", "Run"))
        self.label.setText(_translate("ClientGET", " URL : "))
        self.urlText.setText(_translate("ClientGET", "/"))
        self.label_3.setText(_translate("ClientGET", "Function"))
        self.label_4.setText(_translate("ClientGET", "Variables"))
