#!/usr/bin/env python3

import sys
import cgi
import cgitb
from configparser import ConfigParser
from api.database_controller import DatabaseController


cgitb.enable()

form = cgi.FieldStorage()
args = form.keys()
function_call = form.getvalue('function')

definitions_parser = ConfigParser()
definitions_parser.read('definitions.ini')

if not definitions_parser.has_section(function_call):
    print()
    print('{"error": "No valid function specified"}')
    sys.stdout.flush()
    sys.exit()

function_args = definitions_parser.get(function_call, 'args').split(',')
function_query = definitions_parser.get(function_call, 'sql')

args_map = {}
if function_args[0] != 'None':
    for name in function_args:
        if name not in args:
            print()
            print('{"error": "Argument mismatch"}')
            sys.stdout.flush()
            sys.exit()
        else:
            args_map[name] = form.getvalue(name)


database_controller = DatabaseController()
results = database_controller.run_query(function_query, args_map)

print()
print(results)
